	de2i_150_qsys u0 (
		.clk_clk                                    (<connected-to-clk_clk>),                                    //                        clk.clk
		.reset_reset_n                              (<connected-to-reset_reset_n>),                              //                      reset.reset_n
		.pcie_ip_reconfig_togxb_data                (<connected-to-pcie_ip_reconfig_togxb_data>),                //     pcie_ip_reconfig_togxb.data
		.pcie_ip_refclk_export                      (<connected-to-pcie_ip_refclk_export>),                      //             pcie_ip_refclk.export
		.pcie_ip_test_in_test_in                    (<connected-to-pcie_ip_test_in_test_in>),                    //            pcie_ip_test_in.test_in
		.pcie_ip_pcie_rstn_export                   (<connected-to-pcie_ip_pcie_rstn_export>),                   //          pcie_ip_pcie_rstn.export
		.pcie_ip_clocks_sim_clk250_export           (<connected-to-pcie_ip_clocks_sim_clk250_export>),           //         pcie_ip_clocks_sim.clk250_export
		.pcie_ip_clocks_sim_clk500_export           (<connected-to-pcie_ip_clocks_sim_clk500_export>),           //                           .clk500_export
		.pcie_ip_clocks_sim_clk125_export           (<connected-to-pcie_ip_clocks_sim_clk125_export>),           //                           .clk125_export
		.pcie_ip_reconfig_busy_busy_altgxb_reconfig (<connected-to-pcie_ip_reconfig_busy_busy_altgxb_reconfig>), //      pcie_ip_reconfig_busy.busy_altgxb_reconfig
		.pcie_ip_pipe_ext_pipe_mode                 (<connected-to-pcie_ip_pipe_ext_pipe_mode>),                 //           pcie_ip_pipe_ext.pipe_mode
		.pcie_ip_pipe_ext_phystatus_ext             (<connected-to-pcie_ip_pipe_ext_phystatus_ext>),             //                           .phystatus_ext
		.pcie_ip_pipe_ext_rate_ext                  (<connected-to-pcie_ip_pipe_ext_rate_ext>),                  //                           .rate_ext
		.pcie_ip_pipe_ext_powerdown_ext             (<connected-to-pcie_ip_pipe_ext_powerdown_ext>),             //                           .powerdown_ext
		.pcie_ip_pipe_ext_txdetectrx_ext            (<connected-to-pcie_ip_pipe_ext_txdetectrx_ext>),            //                           .txdetectrx_ext
		.pcie_ip_pipe_ext_rxelecidle0_ext           (<connected-to-pcie_ip_pipe_ext_rxelecidle0_ext>),           //                           .rxelecidle0_ext
		.pcie_ip_pipe_ext_rxdata0_ext               (<connected-to-pcie_ip_pipe_ext_rxdata0_ext>),               //                           .rxdata0_ext
		.pcie_ip_pipe_ext_rxstatus0_ext             (<connected-to-pcie_ip_pipe_ext_rxstatus0_ext>),             //                           .rxstatus0_ext
		.pcie_ip_pipe_ext_rxvalid0_ext              (<connected-to-pcie_ip_pipe_ext_rxvalid0_ext>),              //                           .rxvalid0_ext
		.pcie_ip_pipe_ext_rxdatak0_ext              (<connected-to-pcie_ip_pipe_ext_rxdatak0_ext>),              //                           .rxdatak0_ext
		.pcie_ip_pipe_ext_txdata0_ext               (<connected-to-pcie_ip_pipe_ext_txdata0_ext>),               //                           .txdata0_ext
		.pcie_ip_pipe_ext_txdatak0_ext              (<connected-to-pcie_ip_pipe_ext_txdatak0_ext>),              //                           .txdatak0_ext
		.pcie_ip_pipe_ext_rxpolarity0_ext           (<connected-to-pcie_ip_pipe_ext_rxpolarity0_ext>),           //                           .rxpolarity0_ext
		.pcie_ip_pipe_ext_txcompl0_ext              (<connected-to-pcie_ip_pipe_ext_txcompl0_ext>),              //                           .txcompl0_ext
		.pcie_ip_pipe_ext_txelecidle0_ext           (<connected-to-pcie_ip_pipe_ext_txelecidle0_ext>),           //                           .txelecidle0_ext
		.pcie_ip_rx_in_rx_datain_0                  (<connected-to-pcie_ip_rx_in_rx_datain_0>),                  //              pcie_ip_rx_in.rx_datain_0
		.pcie_ip_tx_out_tx_dataout_0                (<connected-to-pcie_ip_tx_out_tx_dataout_0>),                //             pcie_ip_tx_out.tx_dataout_0
		.pcie_ip_reconfig_fromgxb_0_data            (<connected-to-pcie_ip_reconfig_fromgxb_0_data>),            // pcie_ip_reconfig_fromgxb_0.data
		.led_external_connection_export             (<connected-to-led_external_connection_export>),             //    led_external_connection.export
		.button_external_connection_export          (<connected-to-button_external_connection_export>),          // button_external_connection.export
		.fir_memory_s2_address                      (<connected-to-fir_memory_s2_address>),                      //              fir_memory_s2.address
		.fir_memory_s2_chipselect                   (<connected-to-fir_memory_s2_chipselect>),                   //                           .chipselect
		.fir_memory_s2_clken                        (<connected-to-fir_memory_s2_clken>),                        //                           .clken
		.fir_memory_s2_write                        (<connected-to-fir_memory_s2_write>),                        //                           .write
		.fir_memory_s2_readdata                     (<connected-to-fir_memory_s2_readdata>),                     //                           .readdata
		.fir_memory_s2_writedata                    (<connected-to-fir_memory_s2_writedata>),                    //                           .writedata
		.fir_memory_s2_byteenable                   (<connected-to-fir_memory_s2_byteenable>),                   //                           .byteenable
		.fir_memory_clk2_clk                        (<connected-to-fir_memory_clk2_clk>),                        //            fir_memory_clk2.clk
		.fir_memory_reset2_reset                    (<connected-to-fir_memory_reset2_reset>),                    //          fir_memory_reset2.reset
		.fir_memory_reset2_reset_req                (<connected-to-fir_memory_reset2_reset_req>),                //                           .reset_req
		.interpo_4_0_s2_address                     (<connected-to-interpo_4_0_s2_address>),                     //             interpo_4_0_s2.address
		.interpo_4_0_s2_chipselect                  (<connected-to-interpo_4_0_s2_chipselect>),                  //                           .chipselect
		.interpo_4_0_s2_clken                       (<connected-to-interpo_4_0_s2_clken>),                       //                           .clken
		.interpo_4_0_s2_write                       (<connected-to-interpo_4_0_s2_write>),                       //                           .write
		.interpo_4_0_s2_readdata                    (<connected-to-interpo_4_0_s2_readdata>),                    //                           .readdata
		.interpo_4_0_s2_writedata                   (<connected-to-interpo_4_0_s2_writedata>),                   //                           .writedata
		.interpo_4_0_s2_byteenable                  (<connected-to-interpo_4_0_s2_byteenable>),                  //                           .byteenable
		.interpo_4_0_clk2_clk                       (<connected-to-interpo_4_0_clk2_clk>),                       //           interpo_4_0_clk2.clk
		.interpo_4_0_reset2_reset                   (<connected-to-interpo_4_0_reset2_reset>),                   //         interpo_4_0_reset2.reset
		.interpo_4_0_reset2_reset_req               (<connected-to-interpo_4_0_reset2_reset_req>),               //                           .reset_req
		.interpo_5_0_s2_address                     (<connected-to-interpo_5_0_s2_address>),                     //             interpo_5_0_s2.address
		.interpo_5_0_s2_chipselect                  (<connected-to-interpo_5_0_s2_chipselect>),                  //                           .chipselect
		.interpo_5_0_s2_clken                       (<connected-to-interpo_5_0_s2_clken>),                       //                           .clken
		.interpo_5_0_s2_write                       (<connected-to-interpo_5_0_s2_write>),                       //                           .write
		.interpo_5_0_s2_readdata                    (<connected-to-interpo_5_0_s2_readdata>),                    //                           .readdata
		.interpo_5_0_s2_writedata                   (<connected-to-interpo_5_0_s2_writedata>),                   //                           .writedata
		.interpo_5_0_s2_byteenable                  (<connected-to-interpo_5_0_s2_byteenable>),                  //                           .byteenable
		.interpo_5_0_clk2_clk                       (<connected-to-interpo_5_0_clk2_clk>),                       //           interpo_5_0_clk2.clk
		.interpo_5_0_reset2_reset                   (<connected-to-interpo_5_0_reset2_reset>),                   //         interpo_5_0_reset2.reset
		.interpo_5_0_reset2_reset_req               (<connected-to-interpo_5_0_reset2_reset_req>),               //                           .reset_req
		.interpo_5_1_clk2_clk                       (<connected-to-interpo_5_1_clk2_clk>),                       //           interpo_5_1_clk2.clk
		.interpo_5_1_s2_address                     (<connected-to-interpo_5_1_s2_address>),                     //             interpo_5_1_s2.address
		.interpo_5_1_s2_chipselect                  (<connected-to-interpo_5_1_s2_chipselect>),                  //                           .chipselect
		.interpo_5_1_s2_clken                       (<connected-to-interpo_5_1_s2_clken>),                       //                           .clken
		.interpo_5_1_s2_write                       (<connected-to-interpo_5_1_s2_write>),                       //                           .write
		.interpo_5_1_s2_readdata                    (<connected-to-interpo_5_1_s2_readdata>),                    //                           .readdata
		.interpo_5_1_s2_writedata                   (<connected-to-interpo_5_1_s2_writedata>),                   //                           .writedata
		.interpo_5_1_s2_byteenable                  (<connected-to-interpo_5_1_s2_byteenable>),                  //                           .byteenable
		.interpo_5_1_reset2_reset                   (<connected-to-interpo_5_1_reset2_reset>),                   //         interpo_5_1_reset2.reset
		.interpo_5_1_reset2_reset_req               (<connected-to-interpo_5_1_reset2_reset_req>),               //                           .reset_req
		.interpo_5_2_s2_address                     (<connected-to-interpo_5_2_s2_address>),                     //             interpo_5_2_s2.address
		.interpo_5_2_s2_chipselect                  (<connected-to-interpo_5_2_s2_chipselect>),                  //                           .chipselect
		.interpo_5_2_s2_clken                       (<connected-to-interpo_5_2_s2_clken>),                       //                           .clken
		.interpo_5_2_s2_write                       (<connected-to-interpo_5_2_s2_write>),                       //                           .write
		.interpo_5_2_s2_readdata                    (<connected-to-interpo_5_2_s2_readdata>),                    //                           .readdata
		.interpo_5_2_s2_writedata                   (<connected-to-interpo_5_2_s2_writedata>),                   //                           .writedata
		.interpo_5_2_s2_byteenable                  (<connected-to-interpo_5_2_s2_byteenable>),                  //                           .byteenable
		.interpo_5_2_clk2_clk                       (<connected-to-interpo_5_2_clk2_clk>),                       //           interpo_5_2_clk2.clk
		.interpo_5_2_reset2_reset                   (<connected-to-interpo_5_2_reset2_reset>),                   //         interpo_5_2_reset2.reset
		.interpo_5_2_reset2_reset_req               (<connected-to-interpo_5_2_reset2_reset_req>),               //                           .reset_req
		.interpo_5_3_s2_address                     (<connected-to-interpo_5_3_s2_address>),                     //             interpo_5_3_s2.address
		.interpo_5_3_s2_chipselect                  (<connected-to-interpo_5_3_s2_chipselect>),                  //                           .chipselect
		.interpo_5_3_s2_clken                       (<connected-to-interpo_5_3_s2_clken>),                       //                           .clken
		.interpo_5_3_s2_write                       (<connected-to-interpo_5_3_s2_write>),                       //                           .write
		.interpo_5_3_s2_readdata                    (<connected-to-interpo_5_3_s2_readdata>),                    //                           .readdata
		.interpo_5_3_s2_writedata                   (<connected-to-interpo_5_3_s2_writedata>),                   //                           .writedata
		.interpo_5_3_s2_byteenable                  (<connected-to-interpo_5_3_s2_byteenable>),                  //                           .byteenable
		.interpo_5_3_clk2_clk                       (<connected-to-interpo_5_3_clk2_clk>),                       //           interpo_5_3_clk2.clk
		.interpo_5_3_reset2_reset                   (<connected-to-interpo_5_3_reset2_reset>),                   //         interpo_5_3_reset2.reset
		.interpo_5_3_reset2_reset_req               (<connected-to-interpo_5_3_reset2_reset_req>),               //                           .reset_req
		.adapt_fir_mem_s2_address                   (<connected-to-adapt_fir_mem_s2_address>),                   //           adapt_fir_mem_s2.address
		.adapt_fir_mem_s2_chipselect                (<connected-to-adapt_fir_mem_s2_chipselect>),                //                           .chipselect
		.adapt_fir_mem_s2_clken                     (<connected-to-adapt_fir_mem_s2_clken>),                     //                           .clken
		.adapt_fir_mem_s2_write                     (<connected-to-adapt_fir_mem_s2_write>),                     //                           .write
		.adapt_fir_mem_s2_readdata                  (<connected-to-adapt_fir_mem_s2_readdata>),                  //                           .readdata
		.adapt_fir_mem_s2_writedata                 (<connected-to-adapt_fir_mem_s2_writedata>),                 //                           .writedata
		.adapt_fir_mem_s2_byteenable                (<connected-to-adapt_fir_mem_s2_byteenable>),                //                           .byteenable
		.adapt_fir_mem_clk2_clk                     (<connected-to-adapt_fir_mem_clk2_clk>),                     //         adapt_fir_mem_clk2.clk
		.adapt_fir_mem_reset2_reset                 (<connected-to-adapt_fir_mem_reset2_reset>),                 //       adapt_fir_mem_reset2.reset
		.adapt_fir_mem_reset2_reset_req             (<connected-to-adapt_fir_mem_reset2_reset_req>),             //                           .reset_req
		.micfilter_cntl_export                      (<connected-to-micfilter_cntl_export>),                      //             micfilter_cntl.export
		.micfilter_rst_export                       (<connected-to-micfilter_rst_export>),                       //              micfilter_rst.export
		.micfilter_adjust_export                    (<connected-to-micfilter_adjust_export>)                     //           micfilter_adjust.export
	);

